name: Docker Hub Publisher Caller
on: workflow_dispatch

jobs:
  docker-hub-publisher-caller:
    uses: maurigvs/ga-self-service/.github/workflows/docker-hub-pipeline.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write