name: Docker Hub Publisher

on:
  workflow_call:
    secrets:
      USER:
        description: 'Docker Hub username'
        required: true
      TOKEN:
        description: 'Docker Hub access token'
        required: true

jobs:
  build-and-test:
    uses: maurigvs/ga-self-service/.github/workflows/build-and-test.yml@main
    with:
      java_version: '17'
      java_distribution: 'temurin'
      cache_type: 'gradle'

  push-image:
    needs: build-and-test
    uses: maurigvs/ga-self-service/.github/workflows/push-image.yml@main
    with:
      java_version: '17'
      java_distribution: 'temurin'
      cache_type: 'gradle'
    secrets: inherit