name: Docker Hub Publisher

on:
  workflow_call:
    secrets:
      USER:
        description: 'Docker Hub username'
        required: true
      TOKEN:
        description: 'Docker Hub access token'
        required: true

env:
  JAVA_VERSION: '17'
  JAVA_DIST: 'temurin'
  CACHE_TYPE: 'gradle'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checking out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Setting up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
          cache: ${{ env.CACHE_TYPE }}

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --console plain

  push-image:
    if: ${{ github.ref_name == 'master' }}
    needs: build-and-test
    name: Push Image
    runs-on: ubuntu-latest
    env:
      REGISTRY: 'docker.io'
      IMAGE_TAG: ${{ github.repository }}:latest

    steps:
      - name: Checking out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Setting up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
          cache: ${{ env.CACHE_TYPE }}

      - name: Building application
        run: ./gradlew bootJar --no-daemon

      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Logging in ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Building image and pushing to ${{ env.REGISTRY }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max