name: Docker Hub Publisher

on:
  workflow_call:
    secrets:
      USER:
        description: 'Docker Hub username'
        required: true
      TOKEN:
        description: 'Docker Hub access token'
        required: true

jobs:
  publisher:
    name: Builder
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      java-version: '17'
      java-dist: 'temurin'
      registry: 'docker.io'
      master-branch: ${{ github.ref_name == 'master' }}
      image-tag: ${{ github.repository }}:latest

    steps:
      - name: Checking out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Generate tag
        uses: maurigvs/ga-self-service/.github/actions/tag-generator@main

      - name: Setting up Java ${{ env.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.java-dist }}

      - name: Setting up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        if: ${{ env.master-branch == true }}
        uses: docker/setup-buildx-action@v3

      - name: Log in ${{ env.registry }}
        if: ${{ env.master-branch == true }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Docker build and push image
        if: ${{ env.master-branch == true }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.image-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max