name: Tag Printer

on:
  push:
    branches:
      - feature/MAESTRO-5595-habemus-github

jobs:
  tag-printer:
    name: Tag Printer
    runs-on: ubuntu-latest
    steps:
      - id: print-tag
        name: Print the tag
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SUBSTRING=${BRANCH_NAME:16:4}
          echo "tag=$SUBSTRING" >> "$GITHUB_OUTPUT"

      - id: read-tag
        name: Read the tag
        env:
          TAG: maestro-${{ steps.print-tag.outputs.tag }}
        run: echo ${{ env.TAG }}