name: Tag Printer

on:
  push:
    branches:
      - feature/MAESTRO-5595-habemus-github

jobs:
  tag-printer:
    runs-on: ubuntu-latest
    steps:
      - id: print-tag
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SUBSTRING=${BRANCH_NAME:8:6}
          echo "tag=$SUBSTRING" >> "$GITHUB_OUTPUT"

      - id: read-tag
        run:
          TAG=${{ steps.print-tag.outputs.tag }}
          echo "$TAG"