name: Tag Printer
on: workflow_call
jobs:
  task-printer:
    runs-on: ubuntu-latest
    steps:
      - id: tag-printer
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SUBSTRING=${BRANCH_NAME:8:6}
          echo "tag=$SUBSTRING" >> "$GITHUB_OUTPUT"

      - id: tag-reader
        run:
          TAG=${{ steps.tag-printer.outputs.tag }}
          echo "$TAG"