name: Tag Printer

on:
  push:
    branches:
      - feature/MAESTRO-5595-habemus-github

jobs:
  tag-printer:
    name: Tag Printer
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.print-tag.outputs.tag }}
    steps:
      - id: print-tag
        name: Print the tag
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SUBSTRING=${BRANCH_NAME:16:4}
          echo "tag=$SUBSTRING" >> "$GITHUB_OUTPUT"

  tag-reader:
    needs: tag-printer
    name: Tag Reader
    runs-on: ubuntu-latest
    env:
      tag: ${{ needs.tag-printer.outputs.tag }}
    steps:
      - id: read-tag
        name: Read the tag
        run: echo "maestro-${{ env.tag }}"