name: Tag Generator
on:
  workflow_call:
    outputs:
      tag:
        description: 'The tag to be used'
        value: ${{ jobs.generator.outputs.tag }}

jobs:
  generator:
    name: Generate Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generator.outputs.tag }}
    steps:
      - id: generator
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SUBSTRING=${BRANCH_NAME:0:4}
          echo "tag=$SUBSTRING" >> "$GITHUB_OUTPUT"